display:
  cycle: true
  inverted: false
  orientation: 90
  trendingmode: false
  showvolume: false
  showrank: false
ticker:
  currency: bitcoin,ethereum,cardano
  fiatcurrency: usd,eur,gbp
  # krakenpairs is only required if using kraken as the exchange, this comma seperated list must match the currency and fiatcurrency list
  # A full list of support Kraken pairs can be found here: https://support.kraken.com/hc/en-us/articles/360000920306-Ticker-pairs
  krakenpairs: XXBTZUSD, XETHZUSD, ADAUSD
  exchange: default
  sparklinedays: 1 
  updatefrequency: 300
